apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: redis-deployment
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
        - image: redis:latest
          name: api-redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
